'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BoardingRoomSystem.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_and_White_Watercolor_Floral_Background_Poster_A2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue and White Watercolor Floral Background Poster A2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChatGPT_Image_Jun_11__2026__12_34_35_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatGPT Image Jun 11, 2026, 12_34_35 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cream_and_Gold_Aesthetic_Watercolor_Poster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cream and Gold Aesthetic Watercolor Poster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Green_and_Beige_Watercolor_Floral_Background_Poster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green and Beige Watercolor Floral Background Poster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grey_and_Blue_Gradient_Stars_LinkedIn_Article_Cover_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grey and Blue Gradient Stars LinkedIn Article Cover Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Professional_background_image_for_student_dashboard_of_boarding_room_finding_system__clean_modern_interface_design__soft_gradients_in_blue_and_white_tones__subtle_geometric_patterns__minimalist_style__organized___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Professional background image for student dashboard of boarding room finding syst"& _ 
                        "em, clean modern interface design, soft gradients in blue and white tones, subtl"& _ 
                        "e geometric patterns, minimalist style, organized  (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Professional_background_image_for_student_dashboard_of_boarding_room_finding_system__clean_modern_interface_design__soft_gradients_in_blue_and_white_tones__subtle_geometric_patterns__minimalist_style__organized___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Professional background image for student dashboard of boarding room finding syst"& _ 
                        "em, clean modern interface design, soft gradients in blue and white tones, subtl"& _ 
                        "e geometric patterns, minimalist style, organized  (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Professional_background_image_for_student_dashboard_of_boarding_room_finding_system__clean_modern_interface_design__soft_gradients_in_blue_and_white_tones__subtle_geometric_patterns__minimalist_style__organized_layo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Professional background image for student dashboard of boarding room finding syst"& _ 
                        "em, clean modern interface design, soft gradients in blue and white tones, subtl"& _ 
                        "e geometric patterns, minimalist style, organized layo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Professional_dark_theme_background_image_for_student_dashboard_of_boarding_room_finding_system__modern_dark_interface_design__deep_navy_blue_and_dark_gray_tones__subtle_geometric_patterns__minimalist_style__orga__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Professional dark theme background image for student dashboard of boarding room f"& _ 
                        "inding system, modern dark interface design, deep navy blue and dark gray tones,"& _ 
                        " subtle geometric patterns, minimalist style, orga (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Professional_dark_theme_background_image_for_student_dashboard_of_boarding_room_finding_system__modern_dark_interface_design__deep_navy_blue_and_dark_gray_tones__subtle_geometric_patterns__minimalist_style__organize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Professional dark theme background image for student dashboard of boarding room f"& _ 
                        "inding system, modern dark interface design, deep navy blue and dark gray tones,"& _ 
                        " subtle geometric patterns, minimalist style, organize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Watercolor_Beige_Classic_Frame_LinkedIn_Article_Cover_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Watercolor Beige Classic Frame LinkedIn Article Cover Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Watercolor_Water_Sea_LinkedIn_Article_Cover_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Watercolor Water Sea LinkedIn Article Cover Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
